# -*- coding: utf-8 -*-
"""Proyecto_Ada_TN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kMRXeQhxSBqcgkRWtUl4l9uneSORsq-u
"""

#!/usr/bin/env python
# -*- coding: utf-8 -*-
# author: Agustina


"""
   Módulo que lanza la aplicación en HTML
   En este se implementó el framework FLASK 
   en combinación con Ngrok para montar el servidor
"""


!pip install flask_ngrok
!pip install pyngrok==4.1.1
!ngrok authtoken 2OhokiiPdAj2opRcxbHsZPLcQol_6vPCHNpUHuDqueFoA78oF

from google.colab import drive
drive.mount('/content/gdrive')

from google.colab import files

files.upload()

from flask.templating import render_template #Importo la librerías Flask para montar el HTML
from flask import Flask, request
from flask_ngrok import run_with_ngrok 

from proceso_cuentas import crear_cuentas

cuentas = crear_cuentas()

template_folder= '/content/gdrive/MyDrive/Colab Notebooks/Proyecto_ADA_TN/template'

app= Flask(__name__, template_folder = template_folder)
run_with_ngrok(app)

@app.route("/")

@app.route("/home")
def home():
  return render_template('home.html')

@app.route('/procesar', methods=['POST'])
def procesar_formulario():
    dni = request.form['dni']
    saludo_dni= cuentas.get(dni).saludo()    
    return render_template('home.html', saludo=saludo_dni ) 
app.run()