# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jTA-0iaOyPYAEM_iNuJAe1L1SpcXhsyy
"""

import datetime 
from datetime import date
from cuenta import Cuenta

def calcular_edad (fecha_nacimiento):
  anio = int (fecha_nacimiento [0:4])
  mes = int (fecha_nacimiento [5:7])
  dia = int (fecha_nacimiento [8:10])
  today = date.today()
  edad= (int(today.year) - anio)
  if mes >= int(today.month):
    if dia > int(today.day):
      return (edad-1)
    elif dia <= int(today.day):
      return edad  
  else:
    return (edad)



class Persona():
  def __init__ (self, dni, nombre, fecha_nacimiento):
    self.dni = dni
    self.nombre = nombre
    self.edad = calcular_edad(fecha_nacimiento)
    self.cuentas = []

  def __str__(self):
    return f"Nombre: {self.nombre}"

  def crear_cuenta (self):
    if self.edad >= 18 and self.edad <=30:
      cuenta = CuentaJoven(30, self.nombre, 2000, self.dni)
      self.cuentas.append(cuenta)
    elif self.edad > 30:
      cuenta= Cuenta(self.nombre, 2000, self.dni)
      self.cuentas.append(cuenta)
    else:
      print("Error, la persona es menor de edad")  
    
    

  def saludo (self):
    return f"{self.nombre}, {date.today()} "