# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jTA-0iaOyPYAEM_iNuJAe1L1SpcXhsyy
"""

import csv
from persona import Persona

def crear_cuentas():
  personas={}
  archivo = open("personas.csv","r")
  archivo_csv = csv.reader(archivo)
  titulos = next(archivo_csv)
  for nombre, dni, fecha_nacimiento in archivo_csv:
    persona= Persona(dni, nombre, fecha_nacimiento)
    personas[dni]= persona
  archivo.close()
  return personas


def archivar_cuentas(lista_cuentas):
  lista_de_tuplas = [('Titular', 'Saldo', 'Nro Cuenta', 'Activa')]
  for elemento in lista_cuentas:
    titular= elemento.titular
    saldo= elemento.saldo
    Ncuenta= elemento.cuenta
    estado= elemento.activa
    lista_de_tuplas.append(titular,saldo,Ncuenta,estado)
  archivo = open ("cuentas.csv", "w", newline=" ") 
  archivo_csv = cvs.write(archivo)
  archivo_csv.writerows(lista_de_tuplas)
  archivo.close() 



def procesar_gastos():
  
  pass

def procesar_depositos():
  pass
  

def procesar_transferencias():
  pass